// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DirContentsRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirContentsRequest) Reset()         { *m = DirContentsRequest{} }
func (m *DirContentsRequest) String() string { return proto.CompactTextString(m) }
func (*DirContentsRequest) ProtoMessage()    {}
func (*DirContentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *DirContentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirContentsRequest.Unmarshal(m, b)
}
func (m *DirContentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirContentsRequest.Marshal(b, m, deterministic)
}
func (m *DirContentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirContentsRequest.Merge(m, src)
}
func (m *DirContentsRequest) XXX_Size() int {
	return xxx_messageInfo_DirContentsRequest.Size(m)
}
func (m *DirContentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DirContentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DirContentsRequest proto.InternalMessageInfo

func (m *DirContentsRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type DirContentsResponse struct {
	Entries              []*DirContentsResponse_Entry `protobuf:"bytes,10,rep,name=entries,proto3" json:"entries,omitempty"`
	ErrorMsg             string                       `protobuf:"bytes,11,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DirContentsResponse) Reset()         { *m = DirContentsResponse{} }
func (m *DirContentsResponse) String() string { return proto.CompactTextString(m) }
func (*DirContentsResponse) ProtoMessage()    {}
func (*DirContentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *DirContentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirContentsResponse.Unmarshal(m, b)
}
func (m *DirContentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirContentsResponse.Marshal(b, m, deterministic)
}
func (m *DirContentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirContentsResponse.Merge(m, src)
}
func (m *DirContentsResponse) XXX_Size() int {
	return xxx_messageInfo_DirContentsResponse.Size(m)
}
func (m *DirContentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DirContentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DirContentsResponse proto.InternalMessageInfo

func (m *DirContentsResponse) GetEntries() []*DirContentsResponse_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *DirContentsResponse) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

type DirContentsResponse_Entry struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDirty              bool     `protobuf:"varint,3,opt,name=isDirty,proto3" json:"isDirty,omitempty"`
	IsDir                bool     `protobuf:"varint,4,opt,name=isDir,proto3" json:"isDir,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	ModTimeSeconds       int64    `protobuf:"varint,6,opt,name=modTimeSeconds,proto3" json:"modTimeSeconds,omitempty"`
	BlockID              []byte   `protobuf:"bytes,7,opt,name=blockID,proto3" json:"blockID,omitempty"`
	PopulatedRegionCount int32    `protobuf:"varint,8,opt,name=populatedRegionCount,proto3" json:"populatedRegionCount,omitempty"`
	PopulatedSize        int64    `protobuf:"varint,9,opt,name=populatedSize,proto3" json:"populatedSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirContentsResponse_Entry) Reset()         { *m = DirContentsResponse_Entry{} }
func (m *DirContentsResponse_Entry) String() string { return proto.CompactTextString(m) }
func (*DirContentsResponse_Entry) ProtoMessage()    {}
func (*DirContentsResponse_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1, 0}
}

func (m *DirContentsResponse_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirContentsResponse_Entry.Unmarshal(m, b)
}
func (m *DirContentsResponse_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirContentsResponse_Entry.Marshal(b, m, deterministic)
}
func (m *DirContentsResponse_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirContentsResponse_Entry.Merge(m, src)
}
func (m *DirContentsResponse_Entry) XXX_Size() int {
	return xxx_messageInfo_DirContentsResponse_Entry.Size(m)
}
func (m *DirContentsResponse_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_DirContentsResponse_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_DirContentsResponse_Entry proto.InternalMessageInfo

func (m *DirContentsResponse_Entry) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *DirContentsResponse_Entry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirContentsResponse_Entry) GetIsDirty() bool {
	if m != nil {
		return m.IsDirty
	}
	return false
}

func (m *DirContentsResponse_Entry) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *DirContentsResponse_Entry) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *DirContentsResponse_Entry) GetModTimeSeconds() int64 {
	if m != nil {
		return m.ModTimeSeconds
	}
	return 0
}

func (m *DirContentsResponse_Entry) GetBlockID() []byte {
	if m != nil {
		return m.BlockID
	}
	return nil
}

func (m *DirContentsResponse_Entry) GetPopulatedRegionCount() int32 {
	if m != nil {
		return m.PopulatedRegionCount
	}
	return 0
}

func (m *DirContentsResponse_Entry) GetPopulatedSize() int64 {
	if m != nil {
		return m.PopulatedSize
	}
	return 0
}

func init() {
	proto.RegisterType((*DirContentsRequest)(nil), "api.DirContentsRequest")
	proto.RegisterType((*DirContentsResponse)(nil), "api.DirContentsResponse")
	proto.RegisterType((*DirContentsResponse_Entry)(nil), "api.DirContentsResponse.Entry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PufsClient is the client API for Pufs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PufsClient interface {
	GetDirContents(ctx context.Context, in *DirContentsRequest, opts ...grpc.CallOption) (*DirContentsResponse, error)
}

type pufsClient struct {
	cc *grpc.ClientConn
}

func NewPufsClient(cc *grpc.ClientConn) PufsClient {
	return &pufsClient{cc}
}

func (c *pufsClient) GetDirContents(ctx context.Context, in *DirContentsRequest, opts ...grpc.CallOption) (*DirContentsResponse, error) {
	out := new(DirContentsResponse)
	err := c.cc.Invoke(ctx, "/api.Pufs/GetDirContents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PufsServer is the server API for Pufs service.
type PufsServer interface {
	GetDirContents(context.Context, *DirContentsRequest) (*DirContentsResponse, error)
}

func RegisterPufsServer(s *grpc.Server, srv PufsServer) {
	s.RegisterService(&_Pufs_serviceDesc, srv)
}

func _Pufs_GetDirContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PufsServer).GetDirContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Pufs/GetDirContents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PufsServer).GetDirContents(ctx, req.(*DirContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pufs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Pufs",
	HandlerType: (*PufsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDirContents",
			Handler:    _Pufs_GetDirContents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4f, 0x4f, 0x3a, 0x31,
	0x10, 0xfd, 0xed, 0x2e, 0xcb, 0x9f, 0xe1, 0x27, 0x87, 0x91, 0xc4, 0x86, 0x83, 0xd9, 0x10, 0x63,
	0xf6, 0xc4, 0x01, 0x2f, 0xde, 0x59, 0x62, 0x38, 0x90, 0x98, 0xe2, 0x17, 0x58, 0x60, 0xc4, 0x46,
	0x68, 0x6b, 0xdb, 0x3d, 0xe0, 0x57, 0xf0, 0x13, 0x7b, 0x33, 0x2d, 0x59, 0x22, 0x8a, 0xb7, 0xf7,
	0x5e, 0x5f, 0xe6, 0xbd, 0xcc, 0x14, 0x3a, 0xa5, 0x16, 0x23, 0x6d, 0x94, 0x53, 0x98, 0x94, 0x5a,
	0x0c, 0x73, 0xc0, 0x42, 0x98, 0x89, 0x92, 0x8e, 0xa4, 0xb3, 0x9c, 0xde, 0x2a, 0xb2, 0x0e, 0x11,
	0x1a, 0xba, 0x74, 0x2f, 0x2c, 0xca, 0xa2, 0xbc, 0xc3, 0x03, 0x1e, 0x7e, 0xc6, 0x70, 0x79, 0x62,
	0xb5, 0x5a, 0x49, 0x4b, 0x78, 0x0f, 0x2d, 0x92, 0xce, 0x08, 0xb2, 0x0c, 0xb2, 0x24, 0xef, 0x8e,
	0xaf, 0x47, 0x3e, 0xe3, 0x8c, 0x75, 0x34, 0x95, 0xce, 0xec, 0x79, 0x6d, 0xc7, 0x01, 0xb4, 0xc9,
	0x18, 0x65, 0xe6, 0x76, 0xc3, 0xba, 0x21, 0xe9, 0xc8, 0x07, 0x1f, 0x31, 0xa4, 0xc1, 0x8e, 0x3d,
	0x88, 0x67, 0x45, 0x68, 0x92, 0xf0, 0x78, 0x56, 0xf8, 0x6e, 0xb2, 0xdc, 0x11, 0x8b, 0x0f, 0xdd,
	0x3c, 0x46, 0x06, 0x2d, 0x61, 0x0b, 0x61, 0xdc, 0x9e, 0x25, 0x59, 0x94, 0xb7, 0x79, 0x4d, 0xb1,
	0x0f, 0x69, 0x80, 0xac, 0x11, 0xf4, 0x03, 0xf1, 0x33, 0xac, 0x78, 0x27, 0x96, 0x86, 0xa9, 0x01,
	0xe3, 0x2d, 0xf4, 0x76, 0x6a, 0xfd, 0x24, 0x76, 0xb4, 0xa0, 0x95, 0x92, 0x6b, 0xcb, 0x9a, 0xe1,
	0xf5, 0x87, 0xea, 0xb3, 0x96, 0x5b, 0xb5, 0x7a, 0x9d, 0x15, 0xac, 0x95, 0x45, 0xf9, 0x7f, 0x5e,
	0x53, 0x1c, 0x43, 0x5f, 0x2b, 0x5d, 0x6d, 0x4b, 0x47, 0x6b, 0x4e, 0x1b, 0xa1, 0xe4, 0x44, 0x55,
	0xd2, 0xb1, 0x76, 0x16, 0xe5, 0x29, 0x3f, 0xfb, 0x86, 0x37, 0x70, 0x71, 0xd4, 0x17, 0xbe, 0x52,
	0x27, 0x84, 0x9e, 0x8a, 0xe3, 0x39, 0x34, 0x1e, 0xab, 0x67, 0x8b, 0x53, 0xe8, 0x3d, 0x90, 0xfb,
	0xb6, 0x5a, 0xbc, 0xfa, 0xbd, 0xec, 0x70, 0xc2, 0x01, 0xfb, 0xeb, 0x0a, 0xc3, 0x7f, 0xcb, 0x66,
	0xf8, 0x00, 0x77, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x75, 0x69, 0x66, 0x28, 0x0d, 0x02, 0x00,
	0x00,
}
